IOAS/Controllers/FacilityController.cs
using IOAS.Filter;
using IOAS.GenericServices;
using IOAS.Infrastructure;
using IOAS.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IOAS.Controllers
{
    [Authorized]
    public class FacilityController : Controller
    {
        #region Tapal
        public ActionResult Tapal()
        {
            //int page = 1;
            CreateTapalModel model = new CreateTapalModel();
            int pagesize = 3;
            ViewBag.Department = Common.GetDepartment();
            ViewBag.Role = Common.GetRoleListByDepId(model.selRole);
            ViewBag.UserList = Common.GetUserListByRoleId(model.selDepartment);
            ViewBag.PIList = Common.GetPIWithDetails();
            ViewBag.TapalCatagory = Common.GetTapalCatagory();
            FacilityService _TS = new FacilityService();
            TapalSearchFieldModel Search = new TapalSearchFieldModel();
            DateTime? ToDate = DateTime.Now;
            DateTime? FromeDate = DateTime.Now.AddDays(-180);
            Search.FromCreatedDate = FromeDate;
            Search.ToCreatedDate = ToDate;
            var UserName = User.Identity.Name;
            var role = Common.GetRoleId(UserName);
            var UserId = Common.GetUserid(UserName);
            ViewBag.Action = Common.GetTapalAction(UserId);
            var AccessRole = Common.GetRoleAccess(UserId, 14);
            if (AccessRole.Count > 0)
            {
                if (AccessRole[0].IsRead == true)
                {
                    model.GetTapalInventryDetails = _TS.GetInventryDetailByUser(1, pagesize, Search, UserId);
                }
                //else if(AccessRole[0].IsRead == true)
            }
            //if (role == 1)
            //{
            //    model.GetTapalInventryDetails = _TS.GetInventryDetail(page, pagesize, Search);
            //}
            //else
            //{
            //    model.GetTapalInventryDetails = _TS.GetInventryDetailByUser(page, pagesize, Search, UserId);
            //}
            //model.T
            return View(model);
        }
        [HttpPost]
        public ActionResult TapalIU(CreateTapalModel model, string tapalType)
        {
            try
            {
                int page = 1;
                int pagesize = 3;
                ViewBag.Department = Common.GetDepartment();
                ViewBag.UserList = Common.GetUserListByRoleId(model.selDepartment);
                ViewBag.Role = Common.GetRoleListByDepId(model.selRole);
                FacilityService _TS = new FacilityService();
                TapalSearchFieldModel Search = new TapalSearchFieldModel();
                DateTime? ToDate = DateTime.Now;
                DateTime? FromeDate = DateTime.Now.AddDays(-180);
                Search.FromCreatedDate = FromeDate;
                Search.ToCreatedDate = ToDate;
                int logged_in_userId = Common.GetUserid(User.Identity.Name);
                int RoleId = Common.GetRoleId(User.Identity.Name);
                ViewBag.Action = Common.GetTapalAction(logged_in_userId);
                var AccessRole = Common.GetRoleAccess(logged_in_userId, 14);
                if (AccessRole.Count > 0)
                {
                    if (AccessRole[0].IsRead == true)
                    {
                        model.GetTapalInventryDetails = _TS.GetInventryDetailByUser(page, pagesize, Search, logged_in_userId);
                    }
                    //else if(AccessRole[0].IsRead == true)
                }
                // if (RoleId == 1)
                // {
                //     model.GetTapalInventryDetails = _TS.GetInventryDetail(page, pagesize, Search);
                // }
                //else
                // {
                //     model.GetTapalInventryDetails = _TS.GetInventryDetailByUser(page, pagesize, Search, logged_in_userId);
                // }
                if (tapalType == "Yes")
                {
                    model.ProjectTabal = true;
                }
                else
                {
                    model.ProjectTabal = false;
                }
                if (ModelState.IsValid)
                {
                    List<DocumentDetailModel> DocDetail = new List<DocumentDetailModel>();
                    if (model.TapalId == 0 && model.files[0] == null)
                    {
                        ViewBag.ErrMsg = "Documents filed is required.";
                        return RedirectToAction("Tapal");
                    }
                    foreach (HttpPostedFileBase file in model.files)
                    {
                        if (file != null)
                        {
                            var allowedExtensions = new[] { ".pdf", ".doc", ".docx", ".png", ".jpeg", ".jpg" };
                            string docname = Path.GetFileName(file.FileName);
                            var docextension = Path.GetExtension(docname);
                            if (!allowedExtensions.Contains(docextension))
                            {
                               TempData["errMsg"] = "Please upload any one of these type doc [.pdf, .doc, .docx, .png, .jpeg, .jpg]";
                                return RedirectToAction("Tapal");
                            }
                            if (docextension == ".jpeg" || docextension == ".png" || docextension == ".jpg")
                            {
                                if (file.ContentLength > 26214400)
                                {
                                    TempData["errMsg"] = "You can upload image up to 20 MB";
                                    return RedirectToAction("Tapal");
                                }
                                string ImgName = System.IO.Path.GetFileName(file.FileName);
                                var fileId = Guid.NewGuid().ToString();
                                ImgName = fileId + "_" + ImgName;
                                file.SaveAs(Server.MapPath("~/Content/TapalDocuments/" + ImgName));
                                DocDetail.Add(new DocumentDetailModel()
                                {
                                    DocName = ImgName,
                                    FileName = file.FileName
                                });
                            }
                            else
                            {
                                string docpath = System.IO.Path.GetFileName(file.FileName);
                                var docfileId = Guid.NewGuid().ToString();
                                var fileName = docfileId + "_" + docpath;
                                /*Save the file in server folder*/
                                file.SaveAs(Server.MapPath("~/Content/TapalDocuments/" + fileName));
                                DocDetail.Add(new DocumentDetailModel()
                                {
                                    DocName = fileName,
                                    FileName = file.FileName
                                });
                            }

                        }
                    }
                    model.DocDetail = DocDetail.ToList();
                    FacilityService TS = new FacilityService();
                    int AddEntry = TS.AddNewEntry(model, logged_in_userId);
                    if (AddEntry == 1 && model.TapalId == 0)
                    {
                        TempData["SuccMsg"] = "New entry has been added successfully";
                    }
                    else if (AddEntry == 1 && model.TapalId > 0)
                    {
                        TempData["SuccMsg"] = "Inward has been updated successfully";
                    }
                    else
                    {
                        TempData["errMsg"] = "Somenthing went wrong please contact administrator";
                    }
                }
                else
                {
                    string messages = string.Join("<br />", ModelState.Values
                                        .SelectMany(x => x.Errors)
                                        .Select(x => x.ErrorMessage));

                    TempData["errMsg"] = messages;
                }
                return RedirectToAction("Tapal");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        public ActionResult SaveInwardEntry(int Action,int Department,int Role, int ToUser, string Remarks, int TapalId,bool PopUpEdit)
        {
            try
            {
                FacilityService _TS = new FacilityService();
                int logged_in_userId = Common.GetUserid(User.Identity.Name);
                int logged_in_RoleId = Common.GetRoleId(User.Identity.Name);
                int Update = _TS.SaveInwardEntry(Action,Department, Role, ToUser, Remarks, TapalId, logged_in_userId, PopUpEdit);
                if (Update == 1)
                {
                    return Json(Update, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(Update, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpGet]
        public JsonResult GetOutwardDetails()
        {
            var Role = Common.GetRoleId(User.Identity.Name);
            var UserId = Common.GetUserid(User.Identity.Name);
            object output = FacilityService.GetOutwardDetails(Role, UserId);
            //object output = FacilityService.GetOutwardDetails(UserId,new ListTapalModel(),new DateFilterModel(),1,5);
            return Json(output, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GetOutwardDetails(ListTapalModel model, DateFilterModel OutwardDate,int pageIndex,int pageSize)
        {

IOAS/Views/Facility/CustomSelectList.cshtml
@model IEnumerable<IOAS.Models.SRBItemDetailsModel>
@using System.Linq;
<div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th></th>
                        <th><b>Item Category</b></th>
                        <th><b>Item Name</b></th>
                        <th><b>Item Number</b></th>
                        <th><b>Quantity</b></th>
                        <th><b>Buyback Value</b></th>
                    </tr>

                    @foreach (var item in Model)
                    {

                        var chckBox = "chckBox_" + item.SRBDeactivationId;
                        var sellist = ViewBag.selItems as string[];
                        <tr>
                            <td>
                                @if (sellist.Contains(item.SRBDeactivationId.ToString()))
                                {
                                    <input type="checkbox" checked onclick="update(this)" id="@chckBox" />

                                }
                                else
                                {
                                    <input type="checkbox" onclick="update(this)" id="@chckBox" />
                                }
                            </td>                     
                            <td>
                                @Html.DisplayFor(m => item.ItemCategory)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.ItemName)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.ItemNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Quantity)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.BuybackValue)
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <a href="javascript:void(0)" class="close-btn clsSelectList">
        <i class="ion-android-cancel"></i>
    </a>
    
</div>

IOAS/Views/Facility/PopupDeactivation.cshtml
@model IOAS.Models.SRBItemDetailsModel

<div class="row mt30">
    <div id="BuybackModal" class="modal fade" role="dialog">
        @using (Html.BeginForm("PopupDeactivation", "Facility", FormMethod.Post, new { @id = "frmDeactivate", role = "form", enctype = "multipart/form-data" }))
        {
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                           <h3 class="modal-title">Item Details</h3>
                       
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-md-6">
                                    <div class="ls-dts">
                                        <p>
                                            <span>Item Category</span>
                                            <b>@Html.DisplayFor(m => m.ItemName)</b>
                                        </p>
                                    </div>
                                    <div class="ls-dts">
                                        <p>
                                            <span>Item Number</span>
                                            <b>@Html.DisplayFor(m => m.ItemNumber)</b>
                                        </p>
                                    </div>
                                    <div class="ls-dts">
                                        <p>
                                            <span>Item Value</span>
                                            <b>@Html.DisplayFor(m => m.ItemValue)</b>
                                            @Html.HiddenFor(m=>m.SRBDetailId)
                                        </p>
                                    </div>


                                </div>
                                <div class="col-md-6">
                                    
                                    <div class="ls-dts">
                                        <p>
                                            <span>Item Name</span>
                                            <b>@Html.DisplayFor(m => m.ItemName)</b>
                                        </p>
                                    </div>
                                    <div class="ls-dts">
                                        <p>
                                            <span>Quantity</span>
                                            <b>@Html.DisplayFor(m => m.Quantity)</b>
                                        </p>
                                    </div>

                                </div>
                                <div class="col-md-12">
                                    <div class="col-md-6 pd-null">
                                        <div class="form-group custom-form-group">
                                            <label>Buyback Value</label>
                                            @Html.TextBoxFor(model => model.BuybackValue, new { @class = "form-control", @onkeypress = "return isDecimalKey(event)", @autocomplete = "off" })
                                            <div class="txt-error txt-red">@Html.ValidationMessageFor(model => model.BuybackValue)</div>

                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group custom-form-group">
                                            <label>Document</label>
                                            @Html.TextBoxFor(model => model.Attachment, new {@id= "Attachment", type = "file", @class = "txt-wrap" })
                                            <div class="txt-error txt-red">@Html.ValidationMessageFor(model => model.Attachment)</div>
                                            
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group custom-form-group">
                                        <label>Remarks</label>
                                        @Html.TextAreaFor(M => M.Comments, new { @class = "form-control" })
                                        <div class="txt-error txt-red">@Html.ValidationMessageFor(M => M.Comments)</div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        
                            <input type="submit" name="Button" value="Save" class="btn btn-primary" id="btnSave" />&nbsp; &nbsp;<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                       
                    </div>
                </div>

            </div>
        }
    </div>

</div>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    function isDecimalKey(evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode
        if (charCode > 31 && (charCode != 46 && (charCode < 48 || charCode > 57)))
            return false;
        return true;
    }
    $("#btnSubmit").click(function (e) {
        e.preventDefault();
        var isValid = $('#frmDeactivate').valid();
        if (!isValid)
            return false;
        var file = $('#Attachment').val();
        var isValidExten = false;
        if (file != "") {
            var file_size = $('#Attachment')[0].files[0].size;
            var extension = file.substr((file.lastIndexOf('.') + 1)).toLowerCase();
            switch (extension) {
                case 'doc':
                case 'docx':
                case 'pdf':
                    isValidExten = true;
                    break;
                default:
                    isValidExten = false;
            }
            if (isValidExten == false) {
                $('#alert').html("Please upload any one of these type file [doc, docx, pdf].");
                $('#Validation').modal('toggle');
                return false;
            }
            else if (file_size > 5242880) {
                $('#alert').html("You can upload the file up to 5 MB.");
                $('#Validation').modal('toggle');
                return false;
            }
        }
        if (isValid)
            $('#frmDeactivate').submit();

    });
</script>

IOAS/Views/Facility/PopupTapalDetails.cshtml
@model IOAS.Models.TapalDetailsModel
<div class="row-fluid">
    <div id="notify_modal" class="modal fade" daria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-md">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close closepopup" data-dismiss="modal">
                        <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" id="edit-profile">
                        Tapal Details
                    </h4>
                </div>
                <div class="modal-body">

                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-6">
                                <div class="ls-dts">
                                    <p>
                                        <span>Tapal From</span>
                                        <b>@Html.DisplayFor(m => m.FromUser)</b>
                                    </p>
                                </div>
                                <div class="ls-dts">
                                    <p>
                                        <span>Receipt Date</span>
                                        <b>@Html.DisplayFor(m => m.ReceiptDate)</b>
                                    </p>
                                </div>
                                @if (Model.ProjectTabal)
                                {
                                <div class="ls-dts">
                                    <p>
                                        <span>Project Number</span>
                                        <b>@Html.DisplayFor(m => m.ProjectNumber)</b>
                                    </p>
                                </div>
                                }
                            </div>
                            <div class="col-md-6">
                                <div class="ls-dts">
                                    <p>
                                        <span>Tapal Catagory</span>
                                        <b>@Html.DisplayFor(m => m.TapalType)</b>
                                    </p>
                                </div>
                                <div class="ls-dts">
                                    <p>
                                        <span>Sender Detail</span>
                                        <b>@Html.DisplayFor(m => m.SenderDetails)</b>
                                    </p>
                                </div>
                                @if (Model.ProjectTabal)
                                {
                                <div class="ls-dts">
                                    <p>
                                        <span>PI Name</span>
                                        <b>@Html.DisplayFor(m => m.PIName)</b>
                                    </p>
                                </div>
                                }
                            </div>
                            <div class="col-md-12">
                                <div class="ls-dts">
                                    <p>
                                        <span>Remarks</span>
                                        <b>@Html.Raw(Model.Remarks)</b>
                                    </p>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="ls-dts">
                                    <span>Documents Uploaded</span>
                                    @if (Model.DocDetail.Count > 0)
                                    {
                                    foreach (var item in Model.DocDetail)
                                    {
                                    <p class="mt-sm">


                                        <a href="@Url.Action("ShowDocument","Facility",new {TapalDocId=item.TapalDocDetailId, TapalId=item.TabalId })" target="_blank"> @item.FileName</a>
                                    </p>
                                    }
                                    }


                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-default closepopup" data-dismiss="modal">
                        Close
                    </button>

                </div>
            </div>
        </div>
    </div>
</div>

IOAS/Views/Facility/PopupTapalOutward.cshtml
@model IOAS.Models.CreateTapalModel
<div class="row mt30">
    <div id="EditOutwardModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>

                    <h3 class="modal-title">Edit Outward</h3>
                </div>
                <div class="modal-body">
                    <div class="custom-jsgrid-normal">
                        <div class="row">
                            <div class="col-md-12 col-sm-12">
                                <div class="col-md-6">
                                    <div class="form-group custom-form-group">
                                        <label class="required">Action</label>
                                        @Html.DropDownListFor(m => m.selAction, new SelectList(ViewBag.Action, "id", "name"), "Select Action", new { @class = "form-control", @id = "Action" })
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    @Html.HiddenFor(m => m.TapalId)
                                    <div class="form-group custom-form-group">
                                        <label class="required">Mark To</label>
                                        @Html.DropDownListFor(m => m.selDepartment, new SelectList(ViewBag.Department, "id", "name"), "Select Department", new { @class = "form-control", @id = "Department" })
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group custom-form-group">
                                        <label class="required">Role</label>
                                        @Html.DropDownListFor(m => m.selRole, new SelectList(ViewBag.Role, "id", "name"), "Select Role", new { @class = "form-control", @id = "Role" })
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group custom-form-group">
                                        <label class="required">User</label>
                                        @Html.DropDownListFor(m => m.selUser, new SelectList(ViewBag.UserList, "id", "name"), "Select User", new { @class = "form-control", @id = "User" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 col-sm-12">
                                <div class="col-md-12">
                                    <div class="form-group custom-form-group">
                                        <label class="required">Remarks</label>
                                        @Html.TextAreaFor(m => m.Remarks, new { @rows = "2", @cols = "50", @class = "form-control", @id = "Remarks" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">

                    <input type="submit" name="Button" value="Update" class="btn btn-primary" id="btnEdit" />&nbsp; &nbsp;<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                </div>
            </div>

        </div>
    </div>

</div>
<script type="text/javascript">

    $('#Department').change(function () {
        var departmentId = $(this).val();
        $.getJSON("@Url.Action("LoadRoleList", "Facility")", { ID: departmentId },
                    function (dataUser) {
                        var select = $("#Role");
                        select.empty();
                        $.each(dataUser, function (index, itemData) {
                            select.append($('<option/>', {
                                value: itemData.id,
                                text: itemData.name
                            }));
                        });
                    });
    });
    $('#Role').change(function () {
        
        var RoleId = $(this).val();
        $.getJSON("@Url.Action("LoadUserList", "Facility")", { ID: RoleId },       
                    function (dataUser) {
                        
                        var select = $("#User");
                        select.empty();
                        $.each(dataUser, function (index, itemData) {
                            select.append($('<option/>', {
                                value: itemData.id,
                                text: itemData.name
                            }));
                        });
                    });
    });

    $('#btnEdit').click(function () {
        var intTapalId = $('#TapalId').val();
        var intAction = $("#Action").val();
        var intDepartment = $("#Department").val();
        var intRole=$("#Role").val();
        var intUser = $("#User").val();
        var strRemarks = $("#Remarks").val();
        if (intDepartment == "") {
            $("#alert").text("Please select Mark to");
            $('#Validation').modal('show');
            return false;
        } else if (intUser == "" || intUser == null) {
            $("#alert").text("Please select User");
            $('#Validation').modal('show');
            return false;
        }
        else if (strRemarks == "") {
            $("#alert").text("Please write comments");
            $('#Validation').modal('show');
            return false;
        }
        /*Assigned one variable for editing purpose*/
        var IsPopUpEdit = true;
        /*Assigned one variable for editing purpose*/
        var Data = { "Action": intAction, "Department": intDepartment, "Role": intRole, "ToUser": intUser, "Remarks": strRemarks, "TapalId": intTapalId, 'PopUpEdit': IsPopUpEdit }
        $.ajax({
            url: '@Url.Action("SaveInwardEntry", "Facility")',
            type: 'POST',
            contentType: 'application/json',
            dataType: 'json',
            data: JSON.stringify(Data),

            success: function (data) {
                $('#EditOutwardModal').modal('toggle');
                if (data == 1) {
                    $("#alertSuccess").text('Successfully submited');
                    $('#Success').modal('show');
                    reloadOutwart();
                }
                else {
                    $("#FailedAlert").text('Error. Try again!');
                    $('#Failed').modal('show');
                }
            }
        });
    });

</script>