IOAS/Controllers/CoreAccountsController.cs
using IOAS.DataModel;
using IOAS.Filter;
using IOAS.GenericServices;
using IOAS.Infrastructure;
using IOAS.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IOAS.Controllers
{
    [Authorized]
    public class CoreAccountsController : Controller
    {
        CoreAccountsService coreAccountService = new CoreAccountsService();
        private static readonly Object lockObj = new Object();

        #region Payment
        #region Purchase Order
        #region Advance

        public ActionResult AdvanceBillPaymentList()
        {
            //ViewBag.processGuideLineId = 1006;
            //var fe = FlowEngine.Init(1006, 1, 4, "BillId");
            //fe.ProcessInit();
            return View();

        }


        public ActionResult AdvanceBillPayment(int billId = 0)
        {
            try
            {
                var emptyList = new List<MasterlistviewModel>();
                var ptypeList = Common.getprojecttype();
                int firstPType = ptypeList != null ? ptypeList[0].codevalAbbr : 0;
                ViewBag.VendorList = Common.GetVendorList();
                ViewBag.SourceList = Common.GetSourceList();
                ViewBag.BillTypeList = Common.GetBillTypeList();
                ViewBag.TaxPctList = Common.GetCodeControlList("TaxPercentage");
                ViewBag.ProjectTypeList = ptypeList;
                ViewBag.AccountGroupList =
                ViewBag.VendorTDSList =
                ViewBag.TypeOfServiceList =
                ViewBag.AccountHeadList = emptyList;
                ViewBag.DocmentTypeList = Common.GetDocTypeList(29);
                ViewBag.ProjectNumberList = ProjectService.LoadProjecttitledetails(firstPType);
                //ViewBag.AdvPctList = Common.GetAdvancedPercentageList();
                BillEntryModel model = new BillEntryModel();
                if (billId > 0 && Common.ValidateBillOnEdit(billId, "ADV"))
                {
                    model = coreAccountService.GetBillDetails(billId);
                    
                    ViewBag.TypeOfServiceList = Common.GetTypeOfServiceList(model.BillType ?? 0);
                    ViewBag.VendorTDSList = Common.GetVendorTDSList(model.VendorId);
                }
                else
                    model.CheckListDetail = Common.GetCheckedList(29);
                model.InclusiveOfTax_f = false;
                return View(model);

            }
            catch (Exception ex)
            {
                return View();
            }

        }
        public ActionResult AdvanceBillPaymentView(int billId)
        {
            try
            {
                ViewBag.disabled = "disabled";
                var emptyList = new List<MasterlistviewModel>();
                var ptypeList = Common.getprojecttype();
                int firstPType = ptypeList != null ? ptypeList[0].codevalAbbr : 0;
                ViewBag.VendorList = Common.GetVendorList();
                ViewBag.SourceList = Common.GetSourceList();
                ViewBag.BillTypeList = Common.GetBillTypeList();
                ViewBag.TaxPctList = Common.GetCodeControlList("TaxPercentage");
                ViewBag.ProjectTypeList = ptypeList;
                ViewBag.AccountGroupList =
                ViewBag.AccountHeadList = emptyList;
                ViewBag.DocmentTypeList = Common.GetDocTypeList(29);
                ViewBag.ProjectNumberList = ProjectService.LoadProjecttitledetails(firstPType);
                //ViewBag.AdvPctList = Common.GetAdvancedPercentageList();
                BillEntryModel model = new BillEntryModel();

                model = coreAccountService.GetBillDetails(billId);
                var amt = model.BillAmount + model.BillTaxAmount;
                if (amt > 50000)
                    ViewBag.processGuideLineId = 2;
                else
                    ViewBag.processGuideLineId = 3;
                
                ViewBag.TypeOfServiceList = Common.GetTypeOfServiceList(model.BillType ?? 0);
                ViewBag.VendorTDSList = Common.GetVendorTDSList(model.VendorId);

                model.InclusiveOfTax_f = false;
                return View(model);

            }
            catch (Exception ex)
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult AdvanceBillPayment(BillEntryModel model)
        {
            try
            {
                var emptyList = new List<MasterlistviewModel>();
                var ptypeList = Common.getprojecttype();
                int firstPType = ptypeList != null ? ptypeList[0].codevalAbbr : 0;
                ViewBag.VendorList = Common.GetVendorList();
                ViewBag.SourceList = Common.GetSourceList();
                ViewBag.BillTypeList = Common.GetBillTypeList();
                ViewBag.TaxPctList = Common.GetCodeControlList("TaxPercentage");
                ViewBag.ProjectTypeList = ptypeList;
                ViewBag.AccountGroupList =
                ViewBag.AccountHeadList = emptyList;
                //ViewBag.AdvPctList = Common.GetAdvancedPercentageList();
                
                ViewBag.TypeOfServiceList = Common.GetTypeOfServiceList(model.BillType ?? 0);
                ViewBag.DocmentTypeList = Common.GetDocTypeList(29);
                ViewBag.ProjectNumberList = ProjectService.LoadProjecttitledetails(firstPType);
                ViewBag.VendorTDSList = Common.GetVendorTDSList(model.VendorId);
                foreach (var item in model.ExpenseDetail)
                {
                    int headId = item.AccountGroupId ?? 0;
                    item.AccountGroupList = Common.GetAccountGroup(headId);
                    item.AccountHeadList = Common.GetAccountHeadList(headId);
                }
                ModelState.Remove("InvoiceNumber");
                ModelState.Remove("InvoiceDate");
                ModelState.Remove("BankHead");
                if (ModelState.IsValid)
                {
                    string validationMsg = ValidateAdvanceBillPayment(model);
                    if (validationMsg != "Valid")
                    {
                        TempData["errMsg"] = validationMsg;
                        return View(model);
                    }
                    foreach (var item in model.DocumentDetail)
                    {
                        if (item.DocumentFile != null)
                        {
                            var allowedExtensions = new[] { ".pdf", ".doc", ".docx", ".DOC", ".DOCX", ".PDF" };
                            string taxprooffilename = Path.GetFileName(item.DocumentFile.FileName);
                            var docextension = Path.GetExtension(taxprooffilename);
                            if (!allowedExtensions.Contains(docextension))
                            {
                                TempData["errMsg"] = "Please upload any one of these type doc [.pdf, .doc, .docx]";
                                return View(model);
                            }
                        }
                    }
                    int logged_in_user = Common.GetUserid(User.Identity.Name);
                    int result = coreAccountService.AdvanceBillPaymentIU(model, logged_in_user);
                    if (model.BillId == 0 && result > 0)
                    {
                        TempData["succMsg"] = "Advance Bill has been added successfully.";

                        return RedirectToAction("AdvanceBillPaymentList");
                    }
                    else if (model.BillId > 0 && result > 0)
                    {
                        TempData["succMsg"] = "Advance Bill has been updated successfully.";
                        return RedirectToAction("AdvanceBillPaymentList");
                    }
                    else if (result == -2)
                        TempData["errMsg"] = "Advance Bill already exists for this PO Number with the Vendor.";
                    else if (result == -3)
                        TempData["errMsg"] = "Please select the valid commitment from the list.";
                    //else if (result == -4)
                    //    TempData["errMsg"] = "Same invoice number exists for this Vendor.";
                    else
                        TempData["errMsg"] = "Something went wrong please contact administrator.";

                }
                else
                {
                    string messages = string.Join("<br />", ModelState.Values
                                        .SelectMany(x => x.Errors)
                                        .Select(x => x.ErrorMessage));

                    TempData["errMsg"] = messages;
                }
                return View(model);

            }
            catch (Exception ex)
            {
                var emptyList = new List<MasterlistviewModel>();
                var ptypeList = Common.getprojecttype();
                int firstPType = ptypeList != null ? ptypeList[0].codevalAbbr : 0;
                ViewBag.VendorList = Common.GetVendorList();
                ViewBag.SourceList = Common.GetSourceList();
                ViewBag.BillTypeList = Common.GetBillTypeList();
                ViewBag.TaxPctList = Common.GetCodeControlList("TaxPercentage");
                ViewBag.ProjectTypeList = ptypeList;
                ViewBag.AccountGroupList =
                ViewBag.AccountHeadList = emptyList;
                //ViewBag.AdvPctList = Common.GetAdvancedPercentageList();
                
                ViewBag.TypeOfServiceList = Common.GetTypeOfServiceList(model.BillType ?? 0);
                ViewBag.DocmentTypeList = Common.GetDocTypeList(29);
                ViewBag.ProjectNumberList = ProjectService.LoadProjecttitledetails(firstPType);
                ViewBag.VendorTDSList = Common.GetVendorTDSList(model.VendorId);

IOAS/Views/CoreAccounts/AdvanceBillPaymentList.cshtml
@{
    ViewBag.Title = "Bill Payment";
    ViewBag.Subtitle = "Advance Bill List";
    Layout = "~/Views/Shared/_LayoutFluid.cshtml";
}
<div class="row hd-tt-bg">
    <div class="col-md-4">
        <h3>Advance Bill List</h3>
    </div>
    <div id="addnewpage" class="col-md-8 flt-nav-links">

        @*<a href="Javascript:void(0)" id="btnFilter" class="pull-right"> <i class="ion-android-funnel"></i>Filters</a>*@
        <a href="@Url.Action("AdvanceBillPayment")" > <i class="ion-plus"></i>Add New</a>

    </div>
</div>
<div class="row mt30">
    <div class="page-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="custom-jsgrid-normal">
                    <div id="AdvanceBillPaymentList"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@*<input type="hidden" id="processGuideLineId" value="@ViewBag.processGuideLineId" />
@Html.Partial("_ProcessStatus")*@
<script type="text/javascript">
    var errMsg = '@TempData["errMsg"]';
    var succMsg = '@TempData["succMsg"]';
    $(document).ready(function () {
        if (succMsg != '') {
            $('#alertSuccess').html(succMsg);
            $('#Success').modal('toggle');
        }
        else if (errMsg != '') {
            $('#FailedAlert').html(errMsg);
            $('#Failed').modal('toggle');
        }
    });
    var DateField = function (config) {
        jsGrid.Field.call(this, config);
    };

    DateField.prototype = new jsGrid.Field({
        sorter: function (date1, date2) {
            return new Date(date1) - new Date(date2);
        },

        itemTemplate: function (value) {
            return new Date(value).toDateString();
        },

        filterTemplate: function () {
            var now = new Date();
            this._fromPicker = $("<input>").datepicker({ defaultDate: now.setFullYear(now.getFullYear() - 1), changeYear: true });
            this._toPicker = $("<input>").datepicker({ defaultDate: now.setFullYear(now.getFullYear() + 1), changeYear: true });
            return $("<div>").append(this._fromPicker).append(this._toPicker);
        },

        insertTemplate: function (value) {
            return this._insertPicker = $("<input>").datepicker({ defaultDate: new Date() });
        },

        editTemplate: function (value) {
            return this._editPicker = $("<input>").datepicker().datepicker("setDate", new Date(value));
        },

        insertValue: function () {
            return this._insertPicker.datepicker("getDate").toISOString();
        },

        editValue: function () {
            return this._editPicker.datepicker("getDate").toISOString();
        },

        filterValue: function () {
            return {
                from: this._fromPicker.datepicker("getDate"),
                to: this._toPicker.datepicker("getDate")
            };
        }
    });
    jsGrid.fields.date = DateField;
    @*var url ='@Url.Action("AdvanceBillPayment", "CoreAccounts")?billId='
    var urls = '@Url.Action("AdvanceBillPaymentView", "CoreAccounts")?billId='*@
    var db;
    $("#AdvanceBillPaymentList").jsGrid({
        paging: true,
        pageIndex: 1,
        pageSize: 5,
        editing: false,
        filtering: true,
        controller: {

            loadData: function (filter) {
                return $.grep(db, function (ow) {
                    return (!filter.BillNumber || ow.BillNumber.toLowerCase().indexOf(filter.BillNumber.toLowerCase()) > -1)
                   && (!filter.Vendor || ow.Vendor.toLowerCase().indexOf(filter.Vendor.toLowerCase()) > -1)
                   && (!filter.PostedDate.from || new Date(ow.PostedDate) >= filter.PostedDate.from)
                   && (!filter.PostedDate.to || new Date(ow.PostedDate) <= filter.PostedDate.to);
                });
            }

        },

        fields: [
            { name: "SlNo", title: "S.No", editing: false, width: 50 },
            { type: "number", name: "BillId", title: "Id", visible: false },
            { type: "text", name: "BillNumber", title: "Bill Number", editing: false },
            { type: "text", name: "Vendor", title: "Vendor", editing: false },
            { name: "PostedDate", title: "Posted Date", type: "date", width: 100, align: "center" },
            { name: "BillAmount", title: "Bill Amount", editing: false },
            { name: "CreditorAmount", title: "Advance Amount", editing: false },
            { name: "Status", title: "Status", editing: false },
             {
                 type: "control", editButton: false, deleteButton: false, width: 120, title: "Action",

                 itemTemplate: function (value, item) {
                     var $result = jsGrid.fields.control.prototype.itemTemplate.apply(this, arguments);
                     if (item.Status == "Open") {
                         statusList = [{ id: "", name: "Select Action" }, { id: "Edit", name: "Edit" }, { id: "Submit for approval", name: "Submit for approval" }, { id: "View", name: "View" }]

                     }
                     else
                     {
                         statusList = [{ id: "", name: "Select Action" }, { id: "View", name: "View" }]
                     }
                     var $customSelect = $("<select>")
                         .attr("class", "form-control").prop("selectedIndex", "")
                     $.each(statusList, function (index, itemData) {
                         $customSelect.append($('<option/>', {

                             value: itemData.id,
                             text: itemData.name
                         }));
                     });
                     $customSelect.change(function (e) {
                         var selVal = $(this).val();
                         if (selVal == "Edit") {
                             var url = '@Url.Action("AdvanceBillPayment", "CoreAccounts")?billId=' + item.BillId;
                             window.location.href = url;
                         }
                         else if (selVal == "View") {
                             var url = '@Url.Action("AdvanceBillPaymentView", "CoreAccounts")?billId=' + item.BillId;
                             window.location.href = url;
                         }
                         else if (selVal == "Submit for approval") {
                             var choice = confirm("Are you sure, Do you want to submit this bill for approval process?");
                             if (choice === true) {
                                 $.ajax({
                                     type: "POST",
                                     url: '@Url.Action("POWFInit", "CoreAccounts")',
                                     data: {
                                         billId: item.BillId,
                                         transTypeCode : "ADV"
                                     },
                                     success: function (result) {
                                         if (result.status == true) {
                                             $('#alertSuccess').html("Bill has been submitted for approval process successfully.");
                                             $('#Success').modal('toggle');
                                             loadDetails();
                                         } else if (result.status == false) {
                                             $('#FailedAlert').html(result.msg);
                                             $('#Failed').modal('toggle');
                                         }
                                     },
                                     error: function (err) {
                                         console.log("error1 : " + err);
                                     }
                                 });
                             }
                         }
                         $(this).val("");
                         return false;
                         e.stopPropagation();
                     });
                     return $result.add($customSelect);
                 },
                 _createFilterSwitchButton: function () {
                     return this._createOnOffSwitchButton("filtering", this.searchModeButtonClass, false);
                 }
             }


        ],

    });
    $("#AdvanceBillPaymentList").jsGrid("option", "filtering", false);
    loadDetails();
    function loadDetails() {
        $.ajax({
            type: "GET",
            url: '@Url.Action("GetBillPaymentList", "CoreAccounts")',
            data: {typeCode : "ADV"},
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (result) {
                    db = result;
                    $("#AdvanceBillPaymentList").jsGrid({ data: db });
            },
            error: function (err) {
                console.log("error : " + err);
            }

        });
    }
</script>

IOAS/Views/CoreAccounts/CreditNoteList.cshtml
@{
    ViewBag.Title = "Payment";
    ViewBag.Subtitle = "Credit Note List";
    Layout = "~/Views/Shared/_LayoutFluid.cshtml";
}
<div class="row hd-tt-bg">
    <div class="col-md-4">
        <h3>Credit Note List</h3>
    </div>
    <div id="addnewpage" class="col-md-8 flt-nav-links">

        <a href="@Url.Action("CreditNote")"> <i class="ion-plus"></i>Add New</a>

    </div>
</div>
<div class="row mt30">
    <div class="page-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="custom-jsgrid-normal">
                    <div id="CreditNoteList"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var errMsg = '@TempData["errMsg"]';
    var succMsg = '@TempData["succMsg"]';
    $(document).ready(function () {
        if (succMsg != '') {
            $('#alertSuccess').html(succMsg);
            $('#Success').modal('toggle');
        }
        else if (errMsg != '') {
            $('#FailedAlert').html(errMsg);
            $('#Failed').modal('toggle');
        }
    });
    var DateField = function (config) {
        jsGrid.Field.call(this, config);
    };

    DateField.prototype = new jsGrid.Field({
        sorter: function (date1, date2) {
            return new Date(date1) - new Date(date2);
        },

        itemTemplate: function (value) {
            return new Date(value).toDateString();
        },

        filterTemplate: function () {
            var now = new Date();
            this._fromPicker = $("<input>").datepicker({ defaultDate: now.setFullYear(now.getFullYear() - 1), changeYear: true });
            this._toPicker = $("<input>").datepicker({ defaultDate: now.setFullYear(now.getFullYear() + 1), changeYear: true });
            return $("<div>").append(this._fromPicker).append(this._toPicker);
        },

        insertTemplate: function (value) {
            return this._insertPicker = $("<input>").datepicker({ defaultDate: new Date() });
        },

        editTemplate: function (value) {
            return this._editPicker = $("<input>").datepicker().datepicker("setDate", new Date(value));
        },

        insertValue: function () {
            return this._insertPicker.datepicker("getDate").toISOString();
        },

        editValue: function () {
            return this._editPicker.datepicker("getDate").toISOString();
        },

        filterValue: function () {
            return {
                from: this._fromPicker.datepicker("getDate"),
                to: this._toPicker.datepicker("getDate")
            };
        }
    });
    jsGrid.fields.date = DateField;
    var db;
    $("#CreditNoteList").jsGrid({
        paging: true,
        pageIndex: 1,
        pageSize: 5,
        editing: false,
        filtering: true,
        controller: {

            loadData: function (filter) {
                return $.grep(db, function (ow) {
                    return (!filter.CreditNoteNumber || ow.CreditNoteNumber.toLowerCase().indexOf(filter.CreditNoteNumber.toLowerCase()) > -1)
                   && (!filter.InvoiceNumber || ow.InvoiceNumber.toLowerCase().indexOf(filter.InvoiceNumber.toLowerCase()) > -1)
                   && (!filter.PostedDate.from || new Date(ow.PostedDate) >= filter.PostedDate.from)
                   && (!filter.PostedDate.to || new Date(ow.PostedDate) <= filter.PostedDate.to);
                });
            }

        },

        fields: [
            { name: "SlNo", title: "S.No", editing: false, width: 50 },
            { type: "number", name: "CreditNoteId", title: "Id", visible: false },
            { type: "text", name: "CreditNoteNumber", title: "Credit Note Number", editing: false },
            { type: "text", name: "InvoiceNumber", title: "Invoice Number", editing: false },
            { name: "InvoiceDate", title: "Posted Date", type: "date", width: 100, align: "center" },
            { name: "TotalCreditAmount", title: "Amount", editing: false },
            { name: "Status", title: "Status", editing: false },
             {
                 type: "control", editButton: false, deleteButton: false, width: 120, title: "Action",

                 itemTemplate: function (value, item) {
                     var $result = jsGrid.fields.control.prototype.itemTemplate.apply(this, arguments);
                     if (item.Status == "Open") {
                         statusList = [{ id: "", name: "Select Action" }, { id: "Edit", name: "Edit" }, { id: "Approve", name: "Approve" }, { id: "View", name: "View" }]
                     }
                     else
                     {
                         statusList = [{ id: "", name: "Select Action" }, { id: "View", name: "View" }]
                     }
                     var $customSelect = $("<select>")
                         .attr("class", "form-control").prop("selectedIndex", "")
                     $.each(statusList, function (index, itemData) {
                         $customSelect.append($('<option/>', {

                             value: itemData.id,
                             text: itemData.name
                         }));
                     });
                     $customSelect.change(function (e) {
                         var selVal = $(this).val();
                         if (selVal == "Edit") {
                             var url = '@Url.Action("CreditNote", "CoreAccounts")?creditNoteId=' + item.CreditNoteId;
                             window.location.href = url;
                         }
                         else if (selVal == "View") {
                             var url = '@Url.Action("CreditNoteView", "CoreAccounts")?creditNoteId=' + item.CreditNoteId;
                             window.location.href = url;
                         }
                         else if (selVal == "Approve") {
                             var choice = confirm("Are you sure, Do you want to approve this credit note?");
                             if (choice === true) {
                                 $.ajax({
                                     type: "GET",
                                     url: '@Url.Action("ApproveCreditNote", "CoreAccounts")',
                                     data: { id: item.CreditNoteId },
                                     success: function (result) {
                                         if (result == true) {
                                             $('#alertSuccess').html("Credit note has been approved successfully.");
                                             $('#Success').modal('toggle');
                                             loadDetails();
                                         } else if (result == false) {
                                             $('#FailedAlert').html("Something went wrong please contact administrator.");
                                             $('#Failed').modal('toggle');
                                         }
                                     },
                                     error: function (err) {
                                         console.log("error1 : " + err);
                                     }
                                 });
                             }
                         }
                         $(this).val("");
                         return false;
                         e.stopPropagation();
                     });
                     return $result.add($customSelect);
                 },
                 _createFilterSwitchButton: function () {
                     return this._createOnOffSwitchButton("filtering", this.searchModeButtonClass, false);
                 }
             }


        ],

    });
    $("#CreditNoteList").jsGrid("option", "filtering", false);
    loadDetails();
    function loadDetails() {
        $.ajax({
            type: "GET",
            url: '@Url.Action("GetCreditNoteList", "CoreAccounts")',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (result) {
                    db = result;
                    $("#CreditNoteList").jsGrid({ data: db });
            },
            error: function (err) {
                console.log("error : " + err);
            }

        });
    }
</script>